;(function(){
  angular.module('storybook')
  .config(function(storyBookProvider){
    storyBookProvider.Story('selectable')
    .add('touching(NC)')
    .add('unckekingAvailability(NC)')
    .add('directiveParams(NC)')
    .publish();
  })
})();
